language: go

os:
  - linux
  
go: 
  - "1.14.x"
  - tip

env:
  - GO111MODULE=on

install:
  - go mod tidy
  - go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway 
  - go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger 
  - go install github.com/golang/protobuf/protoc-gen-go 
  - go install golang.org/x/tools/cmd/stringer 
  - go install github.com/vektra/mockery/cmd/mockery 
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  
script:
 - ./test.sh
 - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)
